version: '3'

services:
  rabbitmq:
    image: 'rabbitmq:latest'
    container_name: 'my_rabbitmq'
    ports:
      - '5672:5672' # RabbitMQ default port
      - '15672:15672' # RabbitMQ Management plugin port
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=password
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  rabbitmq_data:
